### PR TITLE
27 fix pipeline

### LINKED ISSUE #27: Fix pipeline
- [x] Fix parsing error (blocked on https://github.com/objectionary/eo/issues/2769)
- [x] Ignore `diff` exit code
- [x] remove the trailing newline in the `normalize-phi` output

### PR DESCRIPTION
**Pull request by deemp**
Closes #27

---

## PR-Codex overview
This PR focuses on updating the EO version and making changes to the pipeline script. 

### Detailed summary
- Updated the EO version from 0.34.2 to 0.34.3.
- Added a step to install EO before running the pipeline.
- Modified the pipeline script to include additional steps for normalization and printing expressions.
- Added a Perl command to remove trailing newline in the output file.
- Added a `diff` command to compare the Phi expressions before and after normalization.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

File: pipeline.sh [hunk 1]
```diff
@@ -33,14 +35,17 @@ stack run normalize-phi < "$I" > "$IO" \
...
+printf "\n\nNormalizer succeeded!"
+printf "\n\n* EO expression:\n\n"
+cat app.eo
 printf "\n\n* Phi expression:\n\n"
 cat "$I"
 printf "\n\n* Normalized Phi expression:\n\n"
 cat "$IO"
 printf "\n\n* Diff:\n\n"
-diff "$I" "$IO"
+diff "$I" "$IO" || true
```
Comment (fizruk) [inline pipeline.sh:48]: Why `|| true`?

Comment (deemp) [reply pipeline.sh:48]: `diff` exits with a non-zero code when files differ. 
Here, I compare the initial term and the normalized term, and they may differ.
