### PR TITLE
138 fix the metric for dataless formations

### LINKED ISSUE #138: Fix the metric for dataless formations
Dataless formation clarification:
- "Primitive" = object with delta (e.g. numbers, strings)
- "Dataless" = not primitive and does not have (direct) primitive attributes (attributes bound to primitive)

### PR DESCRIPTION
**Pull request by deemp**
Closes #138

---

## PR-Codex overview
This PR enhances the `eo-phi-normalizer` by improving metrics calculation and adding a new function for counting dataless formations.

### Detailed summary
- Increased `dataless` metric values in `metrics.yaml`
- Added a new function `countDataless` to count dataless formations in bindings
- Updated the inspection logic in `Collect.hs` to utilize the new function

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

File: eo-phi-normalizer/src/Language/EO/Phi/Metrics/Collect.hs [hunk 1]
```diff
@@ -38,34 +38,34 @@ collectMetrics a = execState (inspect a) defaultMetrics
 class Inspectable a where
   inspect :: a -> State Metrics ()
 
+count :: (a -> Bool) -> [a] -> Int
+count x = length . filter x
+
+countDataless :: (MonadState Metrics m) => [Binding] -> m ()
+countDataless bindings = do
+  let countDeltas = count (\case DeltaBinding _ -> True; _ -> False)
+      deltas = countDeltas (bindings <> concatMap (\case AlphaBinding _ (Formation bindings') -> bindings'; _ -> []) bindings)
```
Comment (fizruk) [inline eo-phi-normalizer/src/Language/EO/Phi/Metrics/Collect.hs:47]: Seems like a very bad `case`-oneliner. Why not introduce a helper properly?

File: eo-phi-normalizer/src/Language/EO/Phi/Metrics/Collect.hs [hunk 2]
```diff
@@ -38,34 +38,34 @@ collectMetrics a = execState (inspect a) defaultMetrics
 class Inspectable a where
   inspect :: a -> State Metrics ()
 
+count :: (a -> Bool) -> [a] -> Int
+count x = length . filter x
+
+countDataless :: (MonadState Metrics m) => [Binding] -> m ()
```
Comment (fizruk) [inline eo-phi-normalizer/src/Language/EO/Phi/Metrics/Collect.hs:44]: This function requires documentation and a doctest.

Comment (deemp) [reply eo-phi-normalizer/src/Language/EO/Phi/Metrics/Collect.hs]: added in https://github.com/objectionary/normalizer/pull/142/commits/2fa396e05ce7e7e1e8311ee9b3483d7bde477a15

**Review by fizruk — APPROVED** [review]

File: eo-phi-normalizer/src/Language/EO/Phi/Metrics/Collect.hs [hunk 3]
```diff
@@ -38,34 +45,52 @@ collectMetrics a = execState (inspect a) defaultMetrics
...
+-- >>> countDataless' "⟦ α0 ↦ ξ, α1 ↦ ⟦ Δ ⤍ 00-00-00-00-00-00-00-2A ⟧ ⟧"
+-- 0
+--
+--
+-- >>> countDataless' "⟦ α0 ↦ ξ, α1 ↦ ⟦ α2 ↦ ⟦ Δ ⤍ 00-00-00-00-00-00-00-2A ⟧ ⟧ ⟧"
+-- 1
+countDataless :: (Num a) => [Binding] -> a
+countDataless bindings =
+  let countDeltas = count (\case DeltaBinding _ -> True; _ -> False)
+      nestedBindings = concatMap (\case AlphaBinding _ (Formation bindings') -> bindings'; _ -> []) bindings
```
[the remark this answers is not in the document]
Comment (deemp) [reply eo-phi-normalizer/src/Language/EO/Phi/Metrics/Collect.hs:71]: I see no issues with it  as long as I have only two cases, where the second one is trivial. Feel free to suggest changes.

[the remark this answers is not in the document]
Comment (fizruk) [reply eo-phi-normalizer/src/Language/EO/Phi/Metrics/Collect.hs:71]: I think it makes sense to factor out this `case` into a separate named helper function and use indentation, not `;` for the cases. This is not critical, just a style thing.
